```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(magrittr)
library(brms)
library(lme4)
library(lmerTest)

options(brms.backend = "cmdstanr", mc.cores = 4)
```

```{r}
df = read_csv("http://www.stat.columbia.edu/~gelman/arm/examples/radon/srrs2.dat")

radon = df %>%
    filter(state == "MN") %>%
    mutate(log.radon = log(ifelse(activity==0, .1, activity))) %>%
    select(log.radon, floor, county)

radon
```

# Pooled/non-hierarchical model

```{r warning=FALSE, message=FALSE, results="hide"}
pooled_fit.brm = brm(log.radon ~ floor, data = radon)
```

```{r}
summary(pooled_fit.brm)

plot(pooled_fit.brm, ask = FALSE)

pp_check(pooled_fit.brm)
```

```{r warning=FALSE, message=FALSE, results="hide"}
pooled_fit.lm = lm(log.radon ~ floor, data = radon)
```

```{r}
summary(pooled_fit.lm)

plot(pooled_fit.lm, ask = FALSE)
```

# Hierarchical model

```{r warning=FALSE, message=FALSE, results="hide"}
hierarchical_fit.brm = brm(log.radon ~ floor + (1 + floor | county), data = radon)
```

```{r}
summary(hierarchical_fit.brm)

plot(hierarchical_fit.brm, ask = FALSE)

pp_check(hierarchical_fit.brm)
```

```{r warning=FALSE, message=FALSE, results="hide"}
hierarchical_fit.lm = lmer(log.radon ~ floor + (1 + floor | county), data = radon)
```

```{r}
summary(hierarchical_fit.lm)

plot(hierarchical_fit.lm, ask = FALSE)
```

# Model comparison

```{r}
loo(hierarchical_fit.brm, pooled_fit.brm)
```

```{r}
anova(hierarchical_fit.lm, pooled_fit.lm)
```
